title = "OAD Process"

# List of folder paths where user added custom registered OpenMDAO components
module_folders = []

# Input and output files
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

# Definition of problem driver assuming the OpenMDAO convention "import openmdao.api as om"
driver = "om.ScipyOptimizeDriver(tol=1e-2, optimizer='COBYLA')"

[model.aicraft]
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=50, err_on_non_converge=True, iprint=2, debug_print=True, rtol=1e-3)"
    linear_solver = "om.LinearBlockGS(maxiter=10, err_on_non_converge=True, iprint=2, rtol=1e-3)"
    [model.aicraft.geometry]
        id = "fastga.geometry.legacy"
        propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
    [model.aicraft.aerodynamics_highspeed]
        id = "fastga.aerodynamics.highspeed.legacy"
        propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
        result_folder_path = "D:/tmp"
        use_openvsp = false
    [model.aicraft.aerodynamics_lowspeed]
        id = "fastga.aerodynamics.lowspeed.legacy"
        propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
        result_folder_path = "D:/tmp"
        use_openvsp = false
    [model.aicraft.cycle]
        nonlinear_solver = "om.NonlinearBlockGS(maxiter=50, err_on_non_converge=True, iprint=2, debug_print=True, rtol=1e-3)"
        linear_solver = "om.LinearBlockGS(maxiter=10, err_on_non_converge=True, iprint=2, rtol=1e-3)"
        [model.aicraft.cycle.weight]
            id = "fastga.weight.legacy"
            propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
        [model.aicraft.cycle.performance]
            id = "fastga.performances.sizing"
            propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
        [model.aicraft.cycle.mtow]
            id = "fastga.loop.mtow"
    [model.aicraft.wing_area]
        id = "fastga.loop.wing_area"
    [model.aicraft.tail_areas]
        id = "fastga.handling_qualities.tail_sizing"
        propulsion_id = "fastga.wrapper.propulsion.basicIC_engine"
    [model.aicraft.static_margin]
        id = "fastga.handling_qualities.static_margin"


[optimization]  # This section is needed only if optimization process is run
    [[optimization.design_var]]
        name = "data:geometry:wing:MAC:at25percent:x"
        lower = 2.5
        upper = 3.5

    [[optimization.constraint]]
        name = "data:handling_qualities:static_margin"
        lower = 0.1
        upper = 0.15

    [[optimization.objective]]
        name = "data:mission:sizing:fuel"